apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helm-webapp-cve-processor.fullname" . }}-db-pvc
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "helm-webapp-cve-processor.labels" . | nindent 4 }}
spec:
  storageClassName: 
    {{- include "helm-webapp-cve-processor.database.storageClassName" . | nindent 4 }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.volume.size | default "3Gi" }}
