apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-webapp-cve-processor.fullname" . }}-db-secrets
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "helm-webapp-cve-processor.labels" . | nindent 4 }}
data:
  FLYWAY_URL: {{ printf "jdbc:postgresql://%s:%s/%s" (include "helm-webapp-cve-processor.database.hostname" .) .Values.db.config.port (.Values.db.secrets.database | b64dec) | b64enc }}
  FLYWAY_USER: {{ .Values.db.secrets.username }}
  FLYWAY_PASSWORD: {{ .Values.db.secrets.password }}
  FLYWAY_DEFAULT_SCHEMA: {{ "flyway" | b64enc }}
  DB_DATABASE: {{ .Values.db.secrets.database }}
  DB_USER: {{ .Values.db.secrets.username }}
  DB_PASSWORD: {{ .Values.db.secrets.password }}
  POSTGRES_DB: {{ .Values.db.secrets.database }}
  POSTGRES_USER: {{ .Values.db.secrets.username }}
  POSTGRES_PASSWORD: {{ .Values.db.secrets.password }}
