apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-webapp-cve-processor.fullname" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "helm-webapp-cve-processor.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "helm-webapp-cve-processor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-webapp-cve-processor.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      imagePullSecrets:
        - name: {{ .Release.Name }}-dockerhub
      serviceAccountName: {{ include "helm-webapp-cve-processor.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
