apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "helm-webapp-cve-processor.fullname" . }}
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "helm-webapp-cve-processor.labels" . | nindent 4 }}
spec:
  completions: 1
  parallelism: 1
  
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-webapp-cve-processor.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: "OnFailure"
      imagePullSecrets:
        - name: {{ include "helm-webapp-cve-processor.fullname" . }}-secrets
      serviceAccountName: {{ include "helm-webapp-cve-processor.serviceAccountName" . }}
      initContainers:
        {{- range .Values.initContainers }}
        - name: {{ .name }}
          image: "{{ .repository }}:{{ .tag | default "latest" }}"
          imagePullPolicy: {{ .pullPolicy | default "Always" }}
          command: {{ .command }}
          args: {{ .args }}
          envFrom:
            - secretRef:
                name: {{ include "helm-webapp-cve-processor.fullname" $ }}-db-secrets
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
          envFrom:
            - secretRef:
                name: {{ include "helm-webapp-cve-processor.fullname" . }}-db-secrets
            - configMapRef:
                name: {{ include "helm-webapp-cve-processor.fullname" . }}-db-configmap
