apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-dockerhub
  namespace: '{{ .Release.Namespace }}'
data:
  .dockerconfigjson: {{ .Values.secrets.dockerhubconfigjson }}
type: kubernetes.io/dockerconfigjson
